from selenium.webdriver.common.by import By

locators = {
    "button_email": (By.XPATH, "//button[text()='Use Email or Username']"),
    "button_login": (By.XPATH, "//button[text()='Log In']"),
    "textbox_username": (By.NAME, "username"),
    "textbox_password": (By.NAME, "password"),
    "text_home": (By.LINK_TEXT, "Home"),
    "text_companies": (By.LINK_TEXT, "Companies"),
    "error_password": (By.XPATH, "//p[text()='Incorrect password']"),
    "text_unregistered": (By.XPATH, "//p[text()='Email Not Registered']"),
    "text_continue_register": (By.XPATH, "//p[text()='You can continue by creating new account with this email']"),
    "button_register": (By.XPATH, "//button[text()='Yes, Register']"),
    "button_edit": (By.XPATH, "//button[text()='Edit']"),
    "text_invalid_format_email": (By.XPATH, "//p[text()='Wrong email format']"),
    "button_company": (By.XPATH, "//button[text()='Add Company']"),
    "textbox_company_name": (By.XPATH, "//input[@placeholder='Input Company Name']"),
    "textbox_email_company": (By.XPATH, "//input[@placeholder='Input Email']"),
    "textbox_phone_company": (By.XPATH, "//input[@placeholder='Input Phone']"),
    "dropdown_industry_type": (By.XPATH, "//button[contains(.,'Choose Industry Type')]"),
    "dropdown_company_type": (By.XPATH, "//button[contains(.,'Choose Company Type')]"),
    "dropdown_language": (By.XPATH, "//button[contains(.,'Choose Language')]"),
    "textbox_address_company": (By.XPATH, "//input[@placeholder='Input Address']"),
    "dropdown_country": (By.XPATH, "//button[.//span[contains(normalize-space(.),'Choose Country')]]"),
    "dropdown_province": (By.XPATH, "//button[.//span[normalize-space(text())='Choose Province']]"),
    "dropdown_city": (By.XPATH, "//button[.//span[contains(normalize-space(.),'Choose City')]"),
    "dropdown_district": (By.XPATH, "//button[.//span[contains(normalize-space(.),'Choose District')]"),
    "dropdown_subdistrict": (By.XPATH, "//button[.//span[contains(normalize-space(.),'Choose Sub District')]"),
    "textbox_postal_code": (By.XPATH, "//input[@placeholder='Postal Code']"),
    "button_next": (By.XPATH, "//button[text()='Next']"),
    "text_register_company": (By.XPATH, "//span[text()='Register Company']"),
}